spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-boot-app
            client-secret: your-client-secret
            scope: openid,profile,email,roles
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

        provider:
          keycloak:
            authorization-uri: http://localhost:4444/realms/master/protocol/openid-connect/auth
            token-uri: http://localhost:4444/realms/master/protocol/openid-connect/token
            user-info-uri: http://localhost:4444/realms/master/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:4444/realms/master/protocol/openid-connect/certs
            user-name-attribute: preferred_username


logging:
  level:
    org.springframework.security: DEBUG
    com.example.security: DEBUG