spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-boot-app
            client-secret: your-client-secret
            scope: openid,profile,email,roles
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

        provider:
          keycloak:
            issuer-uri: http://localhost:4444/realms/spring-app-realm
            user-name-attribute: preferred_username
  websecurity:
    # use custom security debug filter
    debug: true

logging:
  level:
    # enable details logging for spring security
    org.springframework.security: TRACE
    com.example.security: DEBUG