spring:
  security:
    oauth2:
      client:
        registration:
          # Beispiel für Azure AD / Entra ID
          azure:
            client-id: ${AZURE_CLIENT_ID:your-client-id}
            client-secret: ${AZURE_CLIENT_SECRET:your-client-secret}
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Azure AD
          
          # Beispiel für Keycloak
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:your-client-id}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:your-client-secret}
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Keycloak
        
        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID:your-tenant-id}/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID:your-tenant-id}/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            jwk-set-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID:your-tenant-id}/discovery/v2.0/keys
            user-name-attribute: preferred_username
          
          keycloak:
            authorization-uri: ${KEYCLOAK_BASE_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:master}/protocol/openid-connect/auth
            token-uri: ${KEYCLOAK_BASE_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:master}/protocol/openid-connect/token
            user-info-uri: ${KEYCLOAK_BASE_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:master}/protocol/openid-connect/userinfo
            jwk-set-uri: ${KEYCLOAK_BASE_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:master}/protocol/openid-connect/certs
            user-name-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG
    com.yourpackage.security: DEBUG